compressionLevel: mixed

enableGlobalCache: true

nmMode: hardlinks-local

nodeLinker: node-modules

npmAuthToken: "${NPM_TOKEN:-NONE}"

npmPublishAccess: public

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-fb0e891a1a0697c298b9ab87113bf8b98ba131c3
  vitest: npm:@voidzero-dev/vite-plus-test@0.0.0-fb0e891a1a0697c298b9ab87113bf8b98ba131c3
  '@voidzero-dev/vite-plus': 0.0.0-fb0e891a1a0697c298b9ab87113bf8b98ba131c3
npmScopes:
  voidzero-dev:
    npmRegistryServer: https://npm.pkg.github.com
    npmAuthToken: ${VP_TOKEN}
