compressionLevel: mixed

enableGlobalCache: true

nmMode: hardlinks-local

nodeLinker: node-modules

npmAuthToken: "${NPM_TOKEN:-NONE}"

npmPublishAccess: public

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-3f2b8a1aa3a77891a7cd7f3a70ca5b3350fca497
  vitest: npm:@voidzero-dev/vite-plus-test@0.0.0-3f2b8a1aa3a77891a7cd7f3a70ca5b3350fca497
  '@voidzero-dev/vite-plus': 0.0.0-3f2b8a1aa3a77891a7cd7f3a70ca5b3350fca497
npmScopes:
  voidzero-dev:
    npmRegistryServer: https://npm.pkg.github.com
    npmAuthToken: ${VP_TOKEN}
