import { defineConfig } from 'vite-plus';

export default defineConfig({
  staged: {
    '*': 'vp fmt',
    '*.{ts,tsx,mjs,js,jsx}': [
      'vp fmt',
      'cross-env NODE_OPTIONS="--max-old-space-size=8192" vp lint --fix',
    ],
    '*.toml': ['taplo format'],
    '*.rs': ['cargo fmt --'],
  },
  lint: {
    plugins: [
      'import',
      'react',
      'typescript',
      'unicorn',
      'promise',
      'jest',
      'jsdoc',
      'jsx-a11y',
      'nextjs',
      'vitest',
      'vue',
    ],
    categories: {
      correctness: 'error',
      perf: 'error',
    },
    env: {
      builtin: true,
      es2026: true,
    },
    ignorePatterns: [
      '**/node_modules',
      '.yarn',
      '.github/helm',
      '.git',
      '.vscode',
      '.yarnrc.yml',
      '.docker',
      '**/.storybook',
      '.coverage',
      '.nx/**',
      'target',
      'test-results',
      '**/dist',
      '**/lib',
      '**/storybook-static',
      '**/web-static',
      '**/public',
      '**/e2e-dist-*',
      '**/static',
      '**/*.gen.ts',
      '**/*.gql',
      '**/*.d.ts',
      'tools/cli/src/webpack/error-handler.js',
      'packages/backend/native/index.d.ts',
      'packages/backend/server/src/__tests__/__snapshots__',
      'packages/common/native/fixtures/**',
      'packages/common/graphql/src/graphql/index.ts',
      'packages/frontend/native/index.d.ts',
      'packages/frontend/native/index.js',
      'packages/frontend/apps/android/App/**',
      'packages/frontend/apps/ios/App/**',
      'tests/blocksuite/snapshots',
      'blocksuite/docs/api/**',
      'packages/frontend/admin/src/config.json',
      '**/test-docs.json',
      '**/test-blocks.json',
    ],
    rules: {
      'react/display-name': 'error',
      'react/rules-of-hooks': 'error',
      'react/exhaustive-deps': 'warn',
      '@typescript-eslint/prefer-for-of': 'error',
      '@typescript-eslint/no-unsafe-function-type': 'error',
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['**/dist'],
              message: "Don't import from dist",
              allowTypeImports: false,
            },
            {
              group: ['**/src'],
              message: "Don't import from src",
              allowTypeImports: false,
            },
          ],
        },
      ],
      'no-await-in-loop': 'allow',
      'no-redeclare': 'allow',
      'promise/no-callback-in-promise': 'allow',
      'typescript/ban-types': 'allow',
      'array-callback-return': 'error',
      eqeqeq: ['error', 'smart'],
      'getter-return': 'error',
      'import/named': 'error',
      'no-self-compare': 'error',
      'no-empty': [
        'error',
        {
          allowEmptyCatch: true,
        },
      ],
      'no-constructor-return': 'error',
      'no-unused-vars': 'off',
      'no-unused-expressions': 'off',
      'no-loss-of-precision': 'off',
      'no-fallthrough': 'error',
      'no-dupe-class-members': 'off',
      'no-unreachable': 'error',
      'no-case-declarations': 'error',
      'no-var': 'error',
      'no-inner-declarations': 'error',
      'no-prototype-builtins': 'error',
      'no-regex-spaces': 'error',
      'react/jsx-no-useless-fragment': 'error',
      'react/no-unknown-property': 'error',
      'react/no-unescaped-entities': 'error',
      'react/require-render-return': 'error',
      'react/jsx-no-target-blank': 'error',
      'react/jsx-no-comment-textnodes': 'error',
      'react/no-array-index-key': 'off',
      'typescript/consistent-type-imports': 'error',
      'typescript/no-non-null-assertion': 'error',
      'typescript/triple-slash-reference': 'error',
      'typescript/no-non-null-asserted-optional-chain': 'error',
      'typescript/no-duplicate-enum-values': 'error',
      'typescript/no-extra-non-null-assertion': 'error',
      'typescript/no-misused-new': 'error',
      'typescript/prefer-for-of': 'error',
      'typescript/no-unsafe-declaration-merging': 'error',
      'typescript/no-unnecessary-type-constraint': 'error',
      'typescript/no-this-alias': [
        'error',
        {
          allowDestructuring: true,
        },
      ],
      'typescript/prefer-as-const': 'error',
      'typescript/no-var-requires': 'error',
      'typescript/no-namespace': [
        'error',
        {
          allowDeclarations: true,
        },
      ],
      'typescript/ban-ts-comment': [
        'error',
        {
          'ts-expect-error': 'allow-with-description',
          'ts-ignore': true,
          'ts-nocheck': true,
          'ts-check': false,
        },
      ],
      'unicorn/prefer-array-some': 'error',
      'unicorn/prefer-array-flat-map': 'off',
      'unicorn/no-useless-promise-resolve-reject': 'error',
      'unicorn/filename-case': [
        'error',
        {
          case: 'kebabCase',
        },
      ],
      'unicorn/prefer-dom-node-dataset': 'error',
      'unicorn/prefer-dom-node-append': 'error',
      'unicorn/prefer-dom-node-remove': 'error',
      'unicorn/prefer-date-now': 'error',
      'unicorn/prefer-blob-reading-methods': 'error',
      'unicorn/no-typeof-undefined': 'error',
      'unicorn/new-for-builtins': 'error',
      'unicorn/prefer-node-protocol': 'error',
      'import/no-cycle': [
        'error',
        {
          ignoreTypes: true,
        },
      ],
      'import/sort-imports': 'error',
      'import/namespace': 'off',
      'import/no-webpack-loader-syntax': 'error',
      'import/no-duplicates': 'error',
      'import/no-import-assign': 'error',
      'import/no-self-import': 'error',
      'no-cond-assign': 'off',
      'no-import-assign': 'off',
      'no-unexpected-multiline': 'error',
      'react/no-unsafe': 'off',
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'off',
      'no-caller': 'off',
      'no-eval': 'off',
      'no-iterator': 'off',
      'no-unassigned-vars': 'off',
      'no-useless-rename': 'off',
      'import/default': 'off',
      'jest/expect-expect': 'off',
      'jest/no-conditional-expect': 'off',
      'jest/no-disabled-tests': 'off',
      'jest/no-export': 'off',
      'jest/no-focused-tests': 'off',
      'jest/no-standalone-expect': 'off',
      'jest/require-to-throw-message': 'off',
      'jest/valid-describe-callback': 'off',
      'jest/valid-expect': 'off',
      'jest/valid-title': 'off',
      'jsdoc/check-property-names': 'off',
      'jsdoc/check-tag-names': 'off',
      'jsdoc/implements-on-classes': 'off',
      'jsdoc/no-defaults': 'off',
      'jsdoc/require-property': 'off',
      'jsdoc/require-property-description': 'off',
      'jsdoc/require-property-name': 'off',
      'jsdoc/require-property-type': 'off',
      'jsdoc/require-yields': 'off',
      'jsx-a11y/alt-text': 'off',
      'jsx-a11y/anchor-has-content': 'off',
      'jsx-a11y/anchor-is-valid': 'off',
      'jsx-a11y/aria-activedescendant-has-tabindex': 'off',
      'jsx-a11y/aria-props': 'off',
      'jsx-a11y/aria-proptypes': 'off',
      'jsx-a11y/aria-role': 'off',
      'jsx-a11y/aria-unsupported-elements': 'off',
      'jsx-a11y/autocomplete-valid': 'off',
      'jsx-a11y/click-events-have-key-events': 'off',
      'jsx-a11y/heading-has-content': 'off',
      'jsx-a11y/html-has-lang': 'off',
      'jsx-a11y/iframe-has-title': 'off',
      'jsx-a11y/img-redundant-alt': 'off',
      'jsx-a11y/label-has-associated-control': 'off',
      'jsx-a11y/lang': 'off',
      'jsx-a11y/media-has-caption': 'off',
      'jsx-a11y/mouse-events-have-key-events': 'off',
      'jsx-a11y/no-access-key': 'off',
      'jsx-a11y/no-aria-hidden-on-focusable': 'off',
      'jsx-a11y/no-autofocus': 'off',
      'jsx-a11y/no-distracting-elements': 'off',
      'jsx-a11y/no-noninteractive-element-interactions': 'off',
      'jsx-a11y/no-noninteractive-tabindex': 'off',
      'jsx-a11y/no-redundant-roles': 'off',
      'jsx-a11y/no-static-element-interactions': 'off',
      'jsx-a11y/prefer-tag-over-role': 'off',
      'jsx-a11y/role-has-required-aria-props': 'off',
      'jsx-a11y/role-supports-aria-props': 'off',
      'jsx-a11y/scope': 'off',
      'jsx-a11y/tabindex-no-positive': 'off',
      '@next/next/google-font-display': 'off',
      '@next/next/google-font-preconnect': 'off',
      '@next/next/inline-script-id': 'off',
      '@next/next/next-script-for-ga': 'off',
      '@next/next/no-assign-module-variable': 'off',
      '@next/next/no-async-client-component': 'off',
      '@next/next/no-before-interactive-script-outside-document': 'off',
      '@next/next/no-css-tags': 'off',
      '@next/next/no-document-import-in-page': 'off',
      '@next/next/no-duplicate-head': 'off',
      '@next/next/no-head-element': 'off',
      '@next/next/no-head-import-in-document': 'off',
      '@next/next/no-html-link-for-pages': 'off',
      '@next/next/no-img-element': 'off',
      '@next/next/no-page-custom-font': 'off',
      '@next/next/no-script-component-in-head': 'off',
      '@next/next/no-styled-jsx-in-document': 'off',
      '@next/next/no-sync-scripts': 'off',
      '@next/next/no-title-in-document-head': 'off',
      '@next/next/no-typos': 'off',
      '@next/next/no-unwanted-polyfillio': 'off',
      'promise/no-new-statics': 'off',
      'promise/valid-params': 'off',
      'react/forward-ref-uses-ref': 'off',
      'react/jsx-props-no-spread-multi': 'off',
      'react/no-did-mount-set-state': 'off',
      'react/no-this-in-sfc': 'off',
      'react/no-will-update-set-state': 'off',
      'react/void-dom-elements-no-children': 'off',
      '@typescript-eslint/no-duplicate-enum-values': 'off',
      '@typescript-eslint/no-extra-non-null-assertion': 'off',
      '@typescript-eslint/no-misused-new': 'off',
      '@typescript-eslint/no-non-null-asserted-optional-chain': 'off',
      '@typescript-eslint/no-this-alias': 'off',
      '@typescript-eslint/no-unnecessary-parameter-property-assignment': 'off',
      '@typescript-eslint/no-unsafe-declaration-merging': 'off',
      '@typescript-eslint/no-useless-empty-export': 'off',
      '@typescript-eslint/prefer-as-const': 'off',
      '@typescript-eslint/prefer-namespace-keyword': 'off',
      '@typescript-eslint/triple-slash-reference': 'off',
      'unicorn/no-await-in-promise-methods': 'off',
      'unicorn/no-empty-file': 'off',
      'unicorn/no-invalid-fetch-options': 'off',
      'unicorn/no-invalid-remove-event-listener': 'off',
      'unicorn/no-single-promise-in-promise-methods': 'off',
      'unicorn/no-thenable': 'off',
      'unicorn/no-useless-length-check': 'off',
      'unicorn/no-useless-spread': 'off',
      'unicorn/prefer-set-size': 'off',
      'unicorn/prefer-string-starts-ends-with': 'off',
      'vitest/consistent-each-for': 'off',
      'vitest/hoisted-apis-on-top': 'off',
      'vitest/no-conditional-tests': 'off',
      'vitest/require-local-test-context-for-concurrent-snapshots': 'off',
      'vitest/warn-todo': 'off',
      'vue/no-arrow-functions-in-watch': 'off',
      'vue/no-deprecated-destroyed-lifecycle': 'off',
      'vue/no-export-in-script-setup': 'off',
      'vue/no-lifecycle-after-await': 'off',
      'vue/no-this-in-before-route-enter': 'off',
      'vue/prefer-import-from-vue': 'off',
      'vue/valid-define-emits': 'off',
      'vue/valid-define-props': 'off',
      'import-x/default': 'off',
      'import-x/namespace': 'off',
      'vitest/expect-expect': 'off',
      'vitest/no-conditional-expect': 'off',
      'vitest/no-disabled-tests': 'off',
      'vitest/no-focused-tests': 'off',
      'vitest/no-standalone-expect': 'off',
      'vitest/require-to-throw-message': 'off',
      'vitest/valid-describe-callback': 'off',
      'vitest/valid-expect': 'off',
      '@typescript-eslint/unified-signatures': 'error',
      '@typescript-eslint/return-await': [
        'error',
        'error-handling-correctness-only',
      ],
    },
    overrides: [
      {
        files: ['packages/backend/**/*.ts'],
        rules: {
          'typescript/consistent-type-imports': 'off',
        },
      },
      {
        files: [
          '*.{spec,test,e2e,stories}.{ts,tsx}',
          'tests/**/*',
          '**/__tests__/**/*',
          'tools/**/*',
        ],
        rules: {
          'typescript/no-non-null-assertion': 'off',
          'typescript/ban-ts-comment': [
            'error',
            {
              'ts-expect-error': false,
              'ts-ignore': true,
              'ts-nocheck': true,
              'ts-check': false,
            },
          ],
        },
      },
      {
        files: ['blocksuite/**/*.ts'],
        rules: {
          'eslint/eqeqeq': 'off',
          'typescript/no-non-null-assertion': 'off',
          'unicorn/prefer-array-some': 'off',
        },
      },
      {
        files: ['tests/blocksuite/**/*.ts'],
        rules: {
          'typescript/ban-ts-comment': 'off',
          'unicorn/prefer-dom-node-dataset': 'off',
          'typescript/consistent-type-imports': 'off',
          'import/no-cycle': 'off',
        },
      },
      {
        files: [
          'packages/**/*.{ts,tsx}',
          'tools/**/*.{ts,tsx}',
          'blocksuite/**/*.{ts,tsx}',
        ],
        rules: {
          'react/exhaustive-deps': [
            'warn',
            {
              additionalHooks:
                '(useAsyncCallback|useCatchEventCallback|useDraggable|useDropTarget|useRefEffect)',
            },
          ],
        },
      },
      {
        files: [
          '**/__tests__/**/*',
          '**/*.stories.tsx',
          '**/*.spec.ts',
          '**/tests/**/*',
          'scripts/**/*',
          '**/benchmark/**/*',
          '**/__debug__/**/*',
          '**/e2e/**/*',
        ],
        rules: {
          'no-restricted-imports': 'off',
        },
      },
      {
        files: ['**/*.{ts,js,mjs}'],
        rules: {
          'react/rules-of-hooks': 'off',
        },
      },
    ],
    options: {
      typeAware: false,
      typeCheck: false,
    },
  },
  fmt: {
    singleQuote: true,
    trailingComma: 'es5',
    tabWidth: 2,
    arrowParens: 'avoid',
    printWidth: 80,
    sortPackageJson: false,
    ignorePatterns: [
      '**/node_modules',
      '.yarn',
      '.github/helm',
      '.git',
      '.vscode',
      '.yarnrc.yml',
      '.docker',
      '**/.storybook',
      '.coverage',
      '.nx/**',
      'target',
      'test-results',
      '**/dist',
      '**/lib',
      '**/storybook-static',
      '**/web-static',
      '**/public',
      '**/e2e-dist-*',
      '**/static',
      '**/*.gen.ts',
      '**/*.gql',
      '**/*.d.ts',
      'tools/cli/src/webpack/error-handler.js',
      'packages/backend/native/index.d.ts',
      'packages/backend/server/src/__tests__/__snapshots__',
      'packages/common/native/fixtures/**',
      'packages/common/graphql/src/graphql/index.ts',
      'packages/frontend/native/index.d.ts',
      'packages/frontend/native/index.js',
      'packages/frontend/apps/android/App/**',
      'packages/frontend/apps/ios/App/**',
      'tests/blocksuite/snapshots',
      'blocksuite/docs/api/**',
      'packages/frontend/admin/src/config.json',
      '**/test-docs.json',
      '**/test-blocks.json',
    ],
  },
});
